#!/bin/bash
# This is a single queue slurm cluster - only one job will
# be executed at a time.
set -e

sudo apt update -y
sudo apt install slurmd slurmctld -y

SLURM=slurm
# detect if using ubuntu 20.04 or later
if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    if [[ "$VERSION_ID" == "20.04" ]]; then
        SLURM=slurm-llnl
    fi
fi


# TODO: this configuration could probably be trimmed quite
# a bit, but it is a good starting point.
sudo tee -a /etc/${SLURM}/slurm.conf > /dev/null <<EOT
# slurm.conf file generated by configurator.html.
# Put this file on all nodes of your cluster.
# See the slurm.conf man page for more information.
#
ClusterName=localcluster
SlurmctldHost=localhost
MpiDefault=none
ProctrackType=proctrack/linuxproc
ReturnToService=2
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/lib/${SLURM}/slurmd
SlurmUser=slurm
StateSaveLocation=/var/lib/${SLURM}/slurmctld
SwitchType=switch/none
TaskPlugin=task/none

#
# TIMERS
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0
# SCHEDULING
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
#
#AccountingStoragePort=
AccountingStorageType=accounting_storage/none
JobCompType=jobcomp/none
JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/none
SlurmctldDebug=info
SlurmctldLogFile=/var/log/${SLURM}/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/${SLURM}/slurmd.log
#
# COMPUTE NODES
NodeName=localhost CPUs=1 RealMemory=500 State=UNKNOWN
PartitionName=localqueue Nodes=ALL Default=YES MaxTime=INFINITE State=UP
EOT

# Start the processes - they don't start automatically after installation
sudo systemctl start slurmctld
sudo systemctl start slurmd

# Set the machine as idle
# TODO: this might not be needed at all
# sudo scontrol update nodename=localhost state=idle

echo "Running slurm commands to verify setup"
set -x

sinfo
squeue
srun echo "Hello from Slurm!"
